# Generated by Django 5.0.6 on 2024-05-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myanu', '0005_alter_user_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myanu.user'),
            preserve_default=False,
        ),
    ]
