# Generated by Django 5.0.6 on 2024-05-17 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myanu', '0006_paragraph_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
